#############################################################################
#
'''Create a program that will play the “cows and bulls” game with the user. The game works like this:

Randomly generate a 4-digit number. Ask the user to guess a 4-digit number. For every digit that the user guessed correctly in the correct place, they have a “cow”. For every digit the user guessed correctly in the wrong place is a “bull.” Every time the user makes a guess, tell them how many “cows” and “bulls” they have. Once the user guesses the correct number, the game is over. Keep track of the number of guesses the user makes throughout teh game and tell the user at the end.

Say the number generated by the computer is 1038. An example interaction could look like this:

  Welcome to the Cows and Bulls Game! 
  Enter a number: 
  >>> 1234
  2 cows, 0 bulls
  >>> 1256
  1 cow, 1 bull
  ...

Until the user guesses the number.
'''
#
#############################################################################

import random

def GenerateRandom():
    RandNum = ""
    i = 0
    while i < 4:
        digit = str(random.randint(0,9))
        if digit not in RandNum:
            RandNum += digit
            i += 1

        
    return RandNum
	
def UserInput():
	Input = input("Guess a 4 digit number :: ")
	if len(Input) != 4:
		print ("Invalid Input :  Please try again !!!")
		UserInput()
		
	return Input
	
def Game():
    attempt = 0
    cow = 0
    bull = 0
    random_num = GenerateRandom()
    print ("Welcome to the Cows and Bulls Game!")
    while cow != 4:
        cow = 0
        bull = 0
        user_input = UserInput()
        for i in range(0,4):
            if random_num[i] == user_input[i]:
                cow += 1
            else:
                bull += 1
        print (user_input," --> ",cow," Cows ",bull," Bulls")
        attempt += 1
        if cow != 4 :
            print ("Let's try again !!!")
    print ("You Won!!!... You guessed the correct number in ",attempt," attempts")
	
if __name__ == "__main__":
	Game()
